services:
  - id: 1
    title: "Enterprise Java Development"
    description: "Building scalable enterprise applications using Java, Spring Boot, and microservices architecture."
    icon: "i-ph-code"
    category: "Development"
    featured: true
    features:
      - "Spring Boot Microservices"
      - "RESTful API Development"
      - "Database Design & Optimization"
      - "Performance Tuning"
      - "Security Implementation (OAuth, JWT)"
      - "100% Code Coverage with TDD"
    pricing:
      hourly: 80
      currency: "USD"
      description: "From $80/hour"
    timeline: "2-12 weeks"
    suitable: "Enterprise, Startups, SMEs"
    technologies:
      - "Java"
      - "Spring Boot"
      - "PostgreSQL"
      - "MongoDB"
      - "Elasticsearch"
      - "AWS"

  - id: 2
    title: "Full-Stack Application Development"
    description: "End-to-end application development with Angular frontend and Java/Spring backend."
    icon: "i-ph-desktop"
    category: "Development"
    featured: true
    features:
      - "Angular Single Page Applications"
      - "Responsive UI Development"
      - "Backend API Integration"
      - "Real-time Features"
      - "Cross-browser Compatibility"
      - "Mobile-responsive Design"
    pricing:
      hourly: 75
      currency: "USD"
      description: "From $75/hour"
    timeline: "3-16 weeks"
    suitable: "All business sizes"
    technologies:
      - "Angular"
      - "TypeScript"
      - "Java"
      - "Spring Boot"
      - "HTML5/CSS3"
      - "Bootstrap"

  - id: 3
    title: "AI & LLM Integration"
    description: "Integrating Large Language Models and AI capabilities into existing applications."
    icon: "i-ph-robot"
    category: "Innovation"
    featured: true
    features:
      - "LLM Integration (GPT, Claude)"
      - "Automated Workflow Design"
      - "Natural Language Processing"
      - "AI-powered Features"
      - "Custom Model Training"
      - "Performance Optimization"
    pricing:
      hourly: 100
      currency: "USD"
      description: "From $100/hour"
    timeline: "4-12 weeks"
    suitable: "Enterprises, Tech Companies"
    technologies:
      - "Python"
      - "LLMs"
      - "OpenAI API"
      - "Machine Learning"
      - "REST APIs"

  - id: 4
    title: "Microservices Architecture"
    description: "Designing and implementing scalable microservices architecture for enterprise applications."
    icon: "i-ph-circles-three"
    category: "Architecture"
    featured: false
    features:
      - "Service Decomposition"
      - "API Gateway Implementation"
      - "Service Discovery"
      - "Circuit Breaker Pattern"
      - "Event-Driven Architecture"
      - "Container Orchestration"
    pricing:
      hourly: 90
      currency: "USD"
      description: "From $90/hour"
    timeline: "4-20 weeks"
    suitable: "Enterprise, Large Teams"
    technologies:
      - "Spring Cloud"
      - "Docker"
      - "Kubernetes"
      - "API Gateway"
      - "Message Queues"
      - "Service Mesh"

  - id: 5
    title: "Database Optimization & Migration"
    description: "Optimizing database performance and migrating between different database systems."
    icon: "i-ph-database"
    category: "Infrastructure"
    featured: false
    features:
      - "Query Optimization"
      - "Index Management"
      - "Database Migration"
      - "NoSQL Implementation"
      - "Caching Strategies"
      - "Performance Monitoring"
    pricing:
      hourly: 85
      currency: "USD"
      description: "From $85/hour"
    timeline: "2-8 weeks"
    suitable: "All business sizes"
    technologies:
      - "MySQL"
      - "PostgreSQL"
      - "MongoDB"
      - "Elasticsearch"
      - "Redis"
      - "Aerospike"

  - id: 6
    title: "Technical Consulting & Code Review"
    description: "Providing expert technical guidance, code reviews, and architectural recommendations."
    icon: "i-ph-magnifying-glass"
    category: "Consulting"
    featured: false
    features:
      - "Architecture Review"
      - "Code Quality Assessment"
      - "Performance Analysis"
      - "Security Audit"
      - "Best Practices Implementation"
      - "Team Mentoring"
    pricing:
      hourly: 95
      currency: "USD"
      description: "From $95/hour"
    timeline: "1-4 weeks"
    suitable: "All business sizes"
    technologies:
      - "Java"
      - "Spring Boot"
      - "Angular"
      - "System Design"
      - "Code Analysis"
      - "Testing Strategies"

process:
  - step: 1
    title: "Requirements Analysis"
    description: "Understanding your project requirements, technical needs, and business goals."
    icon: "i-ph-chat-circle"
    details:
      - "Initial consultation call"
      - "Requirements documentation"
      - "Technical feasibility study"
      - "Timeline and budget estimation"

  - step: 2
    title: "System Design"
    description: "Creating comprehensive system architecture and technical design documents."
    icon: "i-ph-blueprint"
    details:
      - "High-level architecture design"
      - "Database schema design"
      - "API specification"
      - "Technology stack selection"

  - step: 3
    title: "Agile Development"
    description: "Iterative development with regular sprints and continuous feedback."
    icon: "i-ph-code"
    details:
      - "Sprint planning"
      - "Test-driven development"
      - "Regular code reviews"
      - "Continuous integration"

  - step: 4
    title: "Deployment & Support"
    description: "Deploying to production with comprehensive testing and documentation."
    icon: "i-ph-rocket"
    details:
      - "UAT and performance testing"
      - "Production deployment"
      - "Documentation delivery"
      - "Post-deployment support"

packages:
  - name: "Technical Consulting"
    price: 95
    currency: "USD"
    period: "per hour"
    description: "Expert technical advice and code review"
    features:
      - "Architecture review"
      - "Code quality assessment"
      - "Performance optimization"
      - "Security recommendations"
      - "Best practices guidance"
    highlighted: false
    category: "consulting"

  - name: "Full-Stack Development"
    price: 75
    currency: "USD"
    period: "per hour"
    description: "Complete application development services"
    features:
      - "Frontend development (Angular)"
      - "Backend development (Java/Spring)"
      - "Database design"
      - "API development"
      - "Testing & deployment"
      - "Documentation"
    highlighted: true
    category: "development"

  - name: "Enterprise Solutions"
    price: null
    currency: "USD"
    period: "custom pricing"
    description: "Large-scale enterprise application development"
    features:
      - "Microservices architecture"
      - "Scalability planning"
      - "Performance optimization"
      - "Security implementation"
      - "Team coordination"
      - "Long-term support"
    highlighted: false
    category: "enterprise"