expertise:
  - id: 1
    title: "AI-Powered SaaS Platform Development"
    description: "End-to-end development of intelligent SaaS platforms with advanced AI integrations and enterprise-grade architecture."
    icon: "i-ph-robot"
    category: "Platform Development"
    featured: true
    capabilities:
      - "Multi-tenant SaaS architecture design"
      - "Advanced AI integrations (GPT-4, Claude 3.5)"
      - "Real-time systems with WebSockets"
      - "Computer vision and behavioral analysis"
      - "Enterprise security and GDPR compliance"
      - "Microservices with auto-scaling"
    technologies:
      - "React"
      - "TypeScript"
      - "FastAPI"
      - "PostgreSQL"
      - "OpenAI"
      - "AWS"
      - "Docker"
    experience: "ZerobiasAI - Founded and built complete recruitment platform"
    achievements:
      - "Built production-ready SaaS from concept to deployment"
      - "Achieved <100ms database response times"
      - "Implemented 70% faster AI processing through optimization"

  - id: 2
    title: "Enterprise Java Development & Architecture"
    description: "Full-stack enterprise development with Java, Spring Boot, and modern microservices architecture."
    icon: "i-ph-code"
    category: "Enterprise Development"
    featured: true
    capabilities:
      - "Spring Boot microservices architecture"
      - "Enterprise API development and integration"
      - "Database optimization and performance tuning"
      - "Test-driven development with 100% coverage"
      - "OAuth 2.0 and JWT security implementation"
      - "CI/CD pipeline design and deployment"
    technologies:
      - "Java"
      - "Spring Boot"
      - "Angular"
      - "PostgreSQL"
      - "MongoDB"
      - "Elasticsearch"
      - "AWS"
    experience: "Supercoder & SHL Global - 5+ years enterprise development"
    achievements:
      - "Achieved 99.9% application uptime"
      - "Reduced deployment time by 93%"
      - "Led team of 7 engineers"

  - id: 3
    title: "AI & Machine Learning Integration"
    description: "Advanced AI system integration with focus on LLMs, automation, and intelligent decision-making."
    icon: "i-ph-brain"
    category: "AI Innovation"
    featured: true
    capabilities:
      - "Large Language Model integration and optimization"
      - "AI-powered automation workflows"
      - "Machine learning pipeline development"
      - "Natural language processing systems"
      - "Intelligent data analysis and insights"
      - "Real-time AI decision engines"
    technologies:
      - "OpenAI GPT-4"
      - "Claude 3.5"
      - "Python"
      - "FastAPI"
      - "Machine Learning"
      - "LLMs"
    experience: "ZerobiasAI & Supercoder - AI-first platform development"
    achievements:
      - "Reduced manual screening time by 75%"
      - "Built 3 specialized AI interviewers"
      - "90% accuracy in candidate assessment"

  - id: 4
    title: "Technical Leadership & Team Management"
    description: "Leading development teams, mentoring engineers, and driving technical excellence in high-velocity environments."
    icon: "i-ph-users"
    category: "Leadership"
    featured: false
    capabilities:
      - "Cross-functional team coordination"
      - "Technical architecture decision-making"
      - "Code review and quality assurance"
      - "Agile development methodologies"
      - "Developer mentoring and training"
      - "Project planning and execution"
    technologies:
      - "Agile/Scrum"
      - "Git/GitHub"
      - "Code Review"
      - "Technical Documentation"
      - "Team Management"
    experience: "Founder role + Team lead at SHL Global"
    achievements:
      - "Founded and scaled ZerobiasAI from concept"
      - "Mentored team of 7 engineers"
      - "Improved team onboarding efficiency by 70%"

  - id: 5
    title: "Cloud Architecture & DevOps"
    description: "Designing and implementing scalable cloud infrastructure with modern DevOps practices."
    icon: "i-ph-cloud"
    category: "Infrastructure"
    featured: false
    capabilities:
      - "AWS cloud architecture design"
      - "Dockerized microservices deployment"
      - "Auto-scaling and load balancing"
      - "CI/CD pipeline optimization"
      - "Infrastructure as Code"
      - "Performance monitoring and optimization"
    technologies:
      - "AWS"
      - "Docker"
      - "GitHub Actions"
      - "Terraform"
      - "Kubernetes"
      - "Monitoring"
    experience: "All projects - Cloud-first architecture"
    achievements:
      - "Deployed multi-tenant SaaS on AWS"
      - "Achieved enterprise-grade scalability"
      - "Optimized infrastructure costs"

approach:
  - step: 1
    title: "Technical Assessment"
    description: "Understanding the technical requirements, constraints, and opportunities for innovation."
    icon: "i-ph-magnifying-glass"
    details:
      - "System architecture evaluation"
      - "Technology stack assessment"
      - "Performance and scalability analysis"
      - "Security and compliance review"

  - step: 2
    title: "Solution Design"
    description: "Creating comprehensive technical architecture and implementation strategy."
    icon: "i-ph-blueprint"
    details:
      - "High-level system design"
      - "Database and API architecture"
      - "Technology selection and justification"
      - "Risk assessment and mitigation"

  - step: 3
    title: "Implementation & Leadership"
    description: "Hands-on development with team leadership and quality assurance."
    icon: "i-ph-code"
    details:
      - "Agile development practices"
      - "Test-driven development"
      - "Code review and mentoring"
      - "Performance optimization"

  - step: 4
    title: "Delivery & Innovation"
    description: "Ensuring successful deployment with continuous improvement and innovation."
    icon: "i-ph-rocket"
    details:
      - "Production deployment and monitoring"
      - "Performance tuning and optimization"
      - "Documentation and knowledge transfer"
      - "Continuous innovation and enhancement"

collaboration:
  - name: "Technical Leadership"
    description: "Leading technical teams and driving architectural decisions"
    focus:
      - "System architecture and design"
      - "Technology selection and strategy"
      - "Team mentoring and development"
      - "Code quality and best practices"
      - "Performance optimization"
    highlighted: true
    category: "leadership"

  - name: "Full-Stack Development"
    description: "End-to-end application development and system integration"
    focus:
      - "Frontend development (React, Angular)"
      - "Backend development (Java, Python)"
      - "Database design and optimization"
      - "API development and integration"
      - "Testing and deployment"
    highlighted: false
    category: "development"

  - name: "AI & Innovation"
    description: "Advanced AI integration and innovative solution development"
    focus:
      - "AI/ML system integration"
      - "LLM optimization and deployment"
      - "Intelligent automation workflows"
      - "Data analysis and insights"
      - "Innovation and R&D"
    highlighted: true
    category: "innovation"